ID: "001"

model:
  name: ["CNN"]
  n_hid: [64, 128]
  n_filt: [32, 64]
  drop_prob: [0.3, 0.5] 
training:
  batch_size: [32, 64]
  epochs: 50
  learning_rate: [0.001, 0.0005]

Early_stopping:
  perform: True
  patience: 3
  min_delta: 1e-4

dataset:
  train_path: "data/reduced_train.npz"
  val_path:  "data/reduced_val.npz"
