ID: '100'
model:
  name: CNN-LSTM
  n_hid: 64
  n_filt: 64
  drop_prob: 0.3

training:
  batch_size: 32
  learning_rate: 0.001
  epochs: 100

dataset:
  train_path: "data/train.npz" # "data/reduced_train.npz"
  val_path: # "data/reduced_val.npz"
  test_path: "data/test.npz"
